<a href="https://colab.research.google.com/github/atul2017/AIFoundationPandasNumpy/blob/main/ap_numpy_handson_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Extracting numeric data as NumPy arrays for future analysis
votes = np.array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])
costs = np.array(["'800.0'" ,"'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'", "'600.0'", "'700.0'" ,"'550.0'", "'500.0'"])

print("Votes (Array):", votes)
print("Costs (Array):", costs)

Votes (Array): [ 775  787  918   88  166  286 2556  324  504  402]
Costs (Array): ["'800.0'" "'800.0'" "'800.0'" "'300.0'" "'600.0'" "'600.0'" "'600.0'"
 "'700.0'" "'550.0'" "'500.0'"]


#Numpy is Numarical Python and it helps numerical calculations and operations on data

In [ ]:
votes * 2 #Multiply the entire arrays value by 2

array([1550, 1574, 1836,  176,  332,  572, 5112,  648, 1008,  804])

In [ ]:
type(votes)

numpy.ndarray

In [ ]:
np.ndim(votes)

1

In [ ]:
votes.ndim

1

In [ ]:
votes.shape #it says how many values are available in one dimension in values because there is only one dimension available

(10,)

In [ ]:
#extract values from votes array which are greater than 300
votes[votes > 300] #where votes > 300 returns True or False but when you put inside the brackets it put the corresponding values of True only

array([ 775,  787,  918, 2556,  324,  504,  402])

In [ ]:
# Take a sample of 50 restaurants
sample_votes = np.array([775, 787, 918, 88, 166, 286, 2556, 324, 504, 402, 150, 164, 424, 918, 90, 133, 144, 93, 62, 180, 62, 148, 219, 506, 172, 415, 230, 1647, 4884, 133, 286, 540, 2556, 36, 244, 804, 679, 245, 345, 618, 1047, 627, 354, 244, 163, 808, 1720, 868, 520, 299])
sample_costs = np.array([800.0, 800.0, 800.0, 300.0, 600.0, 600.0, 600.0, 700.0, 550.0, 500.0, 600.0, 500.0, 450.0, 800.0, 650.0, 800.0, 700.0, 300.0, 400.0, 500.0, 600.0, 550.0, 600.0, 500.0, 750.0, 500.0, 650.0, 600.0, 750.0, 200.0, 500.0, 800.0, 600.0, 400.0, 300.0, 450.0, 850.0, 300.0, 400.0, 750.0, 450.0, 450.0, 800.0, 800.0, 800.0, 850.0, 400.0, 1200.0, 300.0, 300.0])

# Create a 2D array: rows = restaurants, columns = [votes, costs]
restaurants_data = np.column_stack((sample_votes, sample_costs))

print("2D Array (votes, costs):\n", restaurants_data)
print("Shape:", restaurants_data.shape)
print("Dimensions:", restaurants_data.ndim)  # 2D

2D Array (votes, costs):
 [[ 775.  800.]
 [ 787.  800.]
 [ 918.  800.]
 [  88.  300.]
 [ 166.  600.]
 [ 286.  600.]
 [2556.  600.]
 [ 324.  700.]
 [ 504.  550.]
 [ 402.  500.]
 [ 150.  600.]
 [ 164.  500.]
 [ 424.  450.]
 [ 918.  800.]
 [  90.  650.]
 [ 133.  800.]
 [ 144.  700.]
 [  93.  300.]
 [  62.  400.]
 [ 180.  500.]
 [  62.  600.]
 [ 148.  550.]
 [ 219.  600.]
 [ 506.  500.]
 [ 172.  750.]
 [ 415.  500.]
 [ 230.  650.]
 [1647.  600.]
 [4884.  750.]
 [ 133.  200.]
 [ 286.  500.]
 [ 540.  800.]
 [2556.  600.]
 [  36.  400.]
 [ 244.  300.]
 [ 804.  450.]
 [ 679.  850.]
 [ 245.  300.]
 [ 345.  400.]
 [ 618.  750.]
 [1047.  450.]
 [ 627.  450.]
 [ 354.  800.]
 [ 244.  800.]
 [ 163.  800.]
 [ 808.  850.]
 [1720.  400.]
 [ 868. 1200.]
 [ 520.  300.]
 [ 299.  300.]]
Shape: (50, 2)
Dimensions: 2


In [ ]:
restaurants_data.reshape(-1) #one large flat array - 1D array

array([ 775.,  800.,  787.,  800.,  918.,  800.,   88.,  300.,  166.,
        600.,  286.,  600., 2556.,  600.,  324.,  700.,  504.,  550.,
        402.,  500.,  150.,  600.,  164.,  500.,  424.,  450.,  918.,
        800.,   90.,  650.,  133.,  800.,  144.,  700.,   93.,  300.,
         62.,  400.,  180.,  500.,   62.,  600.,  148.,  550.,  219.,
        600.,  506.,  500.,  172.,  750.,  415.,  500.,  230.,  650.,
       1647.,  600., 4884.,  750.,  133.,  200.,  286.,  500.,  540.,
        800., 2556.,  600.,   36.,  400.,  244.,  300.,  804.,  450.,
        679.,  850.,  245.,  300.,  345.,  400.,  618.,  750., 1047.,
        450.,  627.,  450.,  354.,  800.,  244.,  800.,  163.,  800.,
        808.,  850., 1720.,  400.,  868., 1200.,  520.,  300.,  299.,
        300.])

In [ ]:
np.where(votes>500) #provides all the indices which has votes > 500

(array([0, 1, 2, 6, 8]),)

In [ ]:
votes[np.where(votes>500)] #returns the values which has the value > 500

array([ 775,  787,  918, 2556,  504])

In [ ]:
# STEP 2: Remove commas and single quotes
costs = np.char.replace(costs, ',', '')  # Remove commas np.char is similar to str.replace we use in python
costs = np.char.replace(costs, "'", '')  # Remove single quotes

# STEP 3: Convert the cleaned strings to float
costs = costs.astype(float)

# STEP 4: Confirm the dtype
print("Array dtype after conversion:", costs.dtype)
print("Cleaned costs:", costs)

Array dtype after conversion: float64
Cleaned costs: [800. 800. 800. 300. 600. 600. 600. 700. 550. 500.]


In [ ]:
#Are there any restaurents with cost > 3000?

costs[np.where(costs>3000)].shape[0] > 0


False

#Use Numpy functions as much as possible compare to python - Numpy functions are optimized and runs faster compare to python

In [ ]:
np.any(costs>300) #more simple way to write the line number 26

np.True_

In [ ]:
#Are all restaurents cheaper than 5000? all functions
np.all(costs<5000)

np.True_

In [ ]:
# Extracting numeric data as NumPy arrays for future analysis
votes = np.array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])
costs = np.array(["'800.0'" ,"'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'", "'600.0'", "'700.0'" ,"'550.0'", "'500.0'"])
rate = np.array([4.1, 3.8, 4.0, 2.6, 1.1, 3.5, 4.7, 2.5, 2.8, 3.4])

print("Votes (Array):", votes)
print("Costs (Array):", costs)
print("Ratings (Array):", rate)

Votes (Array): [ 775  787  918   88  166  286 2556  324  504  402]
Costs (Array): ["'800.0'" "'800.0'" "'800.0'" "'300.0'" "'600.0'" "'600.0'" "'600.0'"
 "'700.0'" "'550.0'" "'500.0'"]
Ratings (Array): [4.1 3.8 4.  2.6 1.1 3.5 4.7 2.5 2.8 3.4]


In [ ]:
numeric_data = np.array([
    [4.1, 775.0, 800.0],
    [3.8, 787.0, 800.0],
    [4.0, 918.0, 800.0],
    [2.6, 88.0, 300.0],
    [1.1, 166.0, 600.0],
    [3.5, 286.0, 600.0],
    [4.7, 2556.0, 600.0],
    [2.5, 324.0, 700.0],
    [2.8, 504.0, 550.0],
    [3.4, 402.0, 500.0]
])

print(numeric_data)

[[4.100e+00 7.750e+02 8.000e+02]
 [3.800e+00 7.870e+02 8.000e+02]
 [4.000e+00 9.180e+02 8.000e+02]
 [2.600e+00 8.800e+01 3.000e+02]
 [1.100e+00 1.660e+02 6.000e+02]
 [3.500e+00 2.860e+02 6.000e+02]
 [4.700e+00 2.556e+03 6.000e+02]
 [2.500e+00 3.240e+02 7.000e+02]
 [2.800e+00 5.040e+02 5.500e+02]
 [3.400e+00 4.020e+02 5.000e+02]]


In [ ]:
np.set_printoptions(suppress=True, precision=1) #simplifying the above data
print(numeric_data)

[[   4.1  775.   800. ]
 [   3.8  787.   800. ]
 [   4.   918.   800. ]
 [   2.6   88.   300. ]
 [   1.1  166.   600. ]
 [   3.5  286.   600. ]
 [   4.7 2556.   600. ]
 [   2.5  324.   700. ]
 [   2.8  504.   550. ]
 [   3.4  402.   500. ]]


In [ ]:
print(votes)
np.sort(votes)

[ 775  787  918   88  166  286 2556  324  504  402]


array([  88,  166,  286,  324,  402,  504,  775,  787,  918, 2556])

In [ ]:
np.argsort(votes) #gives indices of values in original votes array if they sorted - the value in indices 3 -4 - 5-7 etc in sorting

array([3, 4, 5, 7, 9, 8, 0, 1, 2, 6])

In [ ]:
costs[np.argsort(votes)]

array(["'300.0'", "'600.0'", "'600.0'", "'700.0'", "'500.0'", "'550.0'",
       "'800.0'", "'800.0'", "'800.0'", "'600.0'"], dtype='<U7')

Occams Razor - Use the simplest method

In [ ]:
#sorting descending order
np.sort(votes)[::-1] #[start:stop:step]

array([2556,  918,  787,  775,  504,  402,  324,  286,  166,   88])

In [ ]:
#if you don't specify first value - starts from index 0 and ends at index 2 - remember 3 is not included
votes[:3]

array([775, 787, 918])

In [ ]:
#if you don't specify last value - starts from index 2 and ends at last number
votes[2:]

array([ 918,   88,  166,  286, 2556,  324,  504,  402])

In [ ]:
#if you specify the step that means every second value from the begining of the array
votes[::2]

array([ 775,  918,  166, 2556,  504])

In [ ]:
#if you specify the step -1 then it reverses the array
votes[::-1]

array([ 402,  504,  324, 2556,  286,  166,   88,  918,  787,  775])

In [ ]:
# sorting on 2d arrays
array_2d = np.array([[34, 11, 8],
                     [7, 45, 18],
                     [9, 23, 20]])

np.sort(array_2d)

array([[ 8, 11, 34],
       [ 7, 18, 45],
       [ 9, 20, 23]])

In [ ]:
np.sort(array_2d,axis=0) #Vertical sorting - sorting columns

array([[ 7, 11,  8],
       [ 9, 23, 18],
       [34, 45, 20]])

In [ ]:
#sorting by ratings

#step 1 extract 1st column
ratings = numeric_data[:,0]

#step 2 get indices of sorted ratings
sorted_int_by_ratings = np.argsort(ratings)

#step 3
numeric_data[sorted_int_by_ratings,:]

array([[   1.1,  166. ,  600. ],
       [   2.5,  324. ,  700. ],
       [   2.6,   88. ,  300. ],
       [   2.8,  504. ,  550. ],
       [   3.4,  402. ,  500. ],
       [   3.5,  286. ,  600. ],
       [   3.8,  787. ,  800. ],
       [   4. ,  918. ,  800. ],
       [   4.1,  775. ,  800. ],
       [   4.7, 2556. ,  600. ]])

In [ ]:
numeric_data[np.argsort(numeric_data[:,0]),:]

array([[   1.1,  166. ,  600. ],
       [   2.5,  324. ,  700. ],
       [   2.6,   88. ,  300. ],
       [   2.8,  504. ,  550. ],
       [   3.4,  402. ,  500. ],
       [   3.5,  286. ,  600. ],
       [   3.8,  787. ,  800. ],
       [   4. ,  918. ,  800. ],
       [   4.1,  775. ,  800. ],
       [   4.7, 2556. ,  600. ]])

In [ ]:
#element-wise multiplications
votes * ratings

array([ 3177.5,  2990.6,  3672. ,   228.8,   182.6,  1001. , 12013.2,
         810. ,  1411.2,  1366.8])

In [ ]:
votes * 5

array([ 3875,  3935,  4590,   440,   830,  1430, 12780,  1620,  2520,
        2010])

In [ ]:
np.array([1,2,3,4,5]) * np.array([1,2,3])

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [ ]:
#Matrix multipication
transformation_matrix = np.array([[1.2, 0.8, 0.5],
                                   [0.5, 1.5, 1.0],
                                   [0.7, 0.6, 1.8]])
transformation_matrix.shape

In [ ]:
numeric_data.shape

Dimension of matrix A = 3X10
Dimension of matrix B = 10X3
Matrix multiplication of AXB is only possible when A matrix column is same as matrix B row which is true in this case.
The outcome matrix size witll be 3X3 = 9
A dimension is = mXn
B dimension is = nXo
Final multiplication matrix dimension witll be mXo


In [ ]:
#np.dot
np.dot(numeric_data,transformation_matrix)

In [ ]:
np.matmul(numeric_data,transformation_matrix) #Another way to Multiply

In [ ]:
numeric_data@transformation_matrix #Another way to Multiply

In [ ]:
 a = np.array([1,2,3,4])

In [ ]:
np.matmul(a,5)

In [ ]:
a @ 5

In [ ]:
np.dot(a,5)

In [ ]:
b = np.array([10,11,12,13])

In [ ]:
np.dot(a,b) # This will add corrospending values of arrays and sum them

There is no difference between matmul and @ when you multiply the matrixes. The np.dot is a dot product.
Numpy works based on vectorization.
Lot of parrallen computing happens in vectorization.


In [ ]:
def categorize_rating(rating):
    """Categorize ratings into high or low."""
    if rating >= 4.0:
        return "High"
    else:
        return "Low"

In [ ]:
categorize_rating(4.2)

In [ ]:
categorize_rating(ratings)

In [ ]:
vect_categorize_rating = np.vectorize(categorize_rating)
vect_categorize_rating

In [ ]:
vect_categorize_rating(ratings)

In [ ]:
def discount_cost(rate, cost):
    """Apply a 10% discount if the rating is 4.0 or higher."""
    if rate >= 4.0:
        return cost * 0.9
    else:
        return cost

In [ ]:
# Vectorize the discount_cost function
vectorized_discount_cost = np.vectorize(discount_cost)

# Apply the vectorized function to 'rate' and 'approx_cost(for two people)'
discounted_costs = vectorized_discount_cost(numeric_data[:, 0], numeric_data[:, 2])

# Display a sample of the discounted costs
print("Discounted Costs (sample):", discounted_costs[:10])

In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10

result = array_2d + scalar
print("Array:\n", array_2d)
print("---"* 10)

print("adding Scalar:", scalar)
print("---"* 10)

print("Result after broadcasting:\n", result)

In [ ]:
# Arrays with the same shape
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

array1 + array2

array([5, 7, 9])

In [ ]:
# Broadcasting a 1D array to a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_1d = np.array([10, 20, 30])

array_2d + array_1d

array([[11, 22, 33],
       [14, 25, 36]])

In [ ]:
# Column matrix (3x1) and row matrix (1x3)
col_matrix = np.array([[1], [2], [3]])
row_matrix = np.array([[10, 20, 30]])

In [ ]:
print(col_matrix.shape, row_matrix.shape)

(3, 1) (1, 3)


In [ ]:
col_matrix + row_matrix

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2], [3, 4]])

In [ ]:
array1 + array2

Broadcasting - Refer class notes and recording

In [ ]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[10], [20]])

In [ ]:
print(array1)
print(array2)

In [ ]:
array1 + array2

In [ ]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[10, 20]])
array1 + array2

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8]).reshape(2,4)
arr2 = np.array([10,11])
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

In [ ]:
array1 = np.array([[1,2,3]])
array2 = np.array([[10],[20],[30]])

array1_tiled = np.tile(array1, array2.shape)
array1_tiled


In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8])
np.split(arr1, 4)

In [ ]:
array_2d = np.array([[1,2,3,4],[5,6,7,8]])
np.split(array_2d,2,axis=0)

In [ ]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

In [ ]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

In [ ]:
np.arange(10,22)