<a href="https://colab.research.google.com/github/atul2017/AIFoundationPandasNumpy/blob/main/ap_numpy_handson_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Define arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.array([8,9,10])

Vertical Stacking - One top of another

Horizontal Stacking - Side by side joining


In [ ]:
np.vstack([array1,array2])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.vstack([array1,array2,array3])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.array([8,9,10,11])

In [ ]:
np.vstack([array1,array2,array3]) #it will not work - if you are stacking rows that is vstack then the number of rows should be matched

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 2 has size 4

In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.array(["8","9","10"])

In [ ]:
np.vstack([array1,array2,array3]) #Typecasted other numbers in String - Sequence - Number -> Float or Number ->String or Float -> String

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['8', '9', '10']], dtype='<U21')

In [ ]:
np.hstack([array1,array2,array3])

array(['1', '2', '3', '4', '5', '6', '8', '9', '10'], dtype='<U21')

In [ ]:
array4 = np.array([[1], [2], [3]])
array5 = np.array([[4], [5], [6]])

# Stack horizontally
hstack_result = np.hstack([array4, array5])

print("Array 4:\n", array4)
print("Array 5:\n", array5)
print("Horizontal Stack:\n", hstack_result)
array4.shape

Array 4:
 [[1]
 [2]
 [3]]
Array 5:
 [[4]
 [5]
 [6]]
Horizontal Stack:
 [[1 4]
 [2 5]
 [3 6]]


(3, 1)

In [ ]:
type([1,2]) #List is mutable and can keep changing

list

In [ ]:
type((1,2)) #tuple is immutable and never changes

tuple

In [ ]:
# Arrays with unequal rows
array6 = np.array([[7], [8]])

hstack_error = np.hstack([array4, array6])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [ ]:
array4 = np.array([[1], [2], [3]])
array5 = np.array([[4], [5], [6]])

np.concatenate([array4,array5], axis=0)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
array4 = np.array([[1], [2], [3]])
array5 = np.array([[4], [5], [6]])

np.concatenate([array4,array5], axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
array_1 = np.array([1,2,3,4])
array_2 = np.array([6,7,8,9])
np.hstack([array_1, array_2])

array([1, 2, 3, 4, 6, 7, 8, 9])

In [ ]:
np.vstack([array_1, array_2])

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [ ]:
np.array([[1,2,2], [2,2,2], [3,3,3]])

array([[1, 2, 2],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
np.concatenate([array_1,array_2], axis=0)

array([1, 2, 3, 4, 6, 7, 8, 9])

In [ ]:
array_1 = np.array([1,2,3,4])
array_2 = np.array([6,7,8,9])
np.concatenate([array_1,array_2], axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1