<a href="https://colab.research.google.com/github/atul2017/AIFoundationPandasNumpy/blob/main/ap_numpy_handson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


votes = np.array([775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])
cost = np.array(["'800.0'" ,"'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'", "'600.0'", "'700.0'" ,"'550.0'", "'500.0'"])

print("votes Array:",votes)
print("Costs Array:",cost)

votes Array: [ 775  787  918   88  166  286 2556  324  504  402]
Costs Array: ["'800.0'" "'800.0'" "'800.0'" "'300.0'" "'600.0'" "'600.0'" "'600.0'"
 "'700.0'" "'550.0'" "'500.0'"]


1. Numpy arrays are always homogenous
2. If you store Int and Float in Numpy array it will convert all int to Float
3. Vice versa cannot happen because you might loose the data if you convert Float to Int
4. Arrays index always start with zero

In [ ]:
np.array([1,2,3.3])


array([1. , 2. , 3.3])

In [ ]:
np.array([1,2,"3.0"]) #String > Float > No

array(['1', '2', '3.0'], dtype='<U21')

In [ ]:
np.array([1,2,3.0], dtype=int) #convert all values in int inside the array

array([1, 2, 3])

In [ ]:
list(range(20)) #generates the sequence of numbers

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
import time
import numpy as np

large_list = list(range(1000000))
large_array = np.arange(1000000);

start = time.time()
list_sum = sum(large_list)
end = time.time()
list_time = end - start

start = time.time()
array_sum = np.sum(large_array)
end = time.time()
array_time = end - start

print("List Time:",list_time)
print("Array Time:",array_time)

List Time: 0.030670881271362305
Array Time: 0.0039331912994384766


In [ ]:
list_time/array_time #Array perfornace is more than the list. In array the values are stores in continous location. In python List the values are stored in
#random memory location which takes more time to access values compare to arrays

7.797963266048373

In [ ]:
votes

array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])

In [ ]:
votes_time_two = votes * 2
votes_time_two

array([1550, 1574, 1836,  176,  332,  572, 5112,  648, 1008,  804])

In [ ]:
type(votes_time_two) #type of the array

numpy.ndarray

In [ ]:
votes_time_two.shape #shape of the array

(10,)

In [ ]:
votes_time_two.ndim #dimension of the array

1

In [ ]:
votes_time_two.size #size of the array

10

In [ ]:
subset_votes = votes
subset_costs = cost

two_d_data = np.array([subset_votes,subset_costs]).T
two_d_data

print("2D Array:\n", two_d_data)
print("Shape:", two_d_data.shape)
print("Dimensions:", two_d_data.ndim)
print("Size:", two_d_data.size)

2D Array:
 [['775' "'800.0'"]
 ['787' "'800.0'"]
 ['918' "'800.0'"]
 ['88' "'300.0'"]
 ['166' "'600.0'"]
 ['286' "'600.0'"]
 ['2556' "'600.0'"]
 ['324' "'700.0'"]
 ['504' "'550.0'"]
 ['402' "'500.0'"]]
Shape: (10, 2)
Dimensions: 2
Size: 20


In [ ]:
np.array([subset_votes,subset_costs]).shape

(2, 10)

In [ ]:
np.arange(1,5) #returns the numpy array

array([1, 2, 3, 4])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,10,.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
cost

array(["'800.0'", "'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'",
       "'600.0'", "'700.0'", "'550.0'", "'500.0'"], dtype='<U7')

In [ ]:
cost = np.char.replace(cost, "'", '') #replace something from the array. First convert the values in the array to char and use replace function
cost

array(['800.0', '800.0', '800.0', '300.0', '600.0', '600.0', '600.0',
       '700.0', '550.0', '500.0'], dtype='<U5')

In [ ]:
cost.astype(float) #convert the array to float

array([800., 800., 800., 300., 600., 600., 600., 700., 550., 500.])

In [ ]:
cost_v2 = np.array(["'800.0'", "'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'",
       "'600.0'", "'700.0'", "'550.0'", "'500.0'"])
cost_v2.astype(float);  #error since you are asking too much to python

ValueError: could not convert string to float: np.str_("'800.0'")

In [ ]:
test_array = np.array(["$12,23", "$11,1111"])
test_array = np.char.replace(test_array, "$", '')
test_array = np.char.replace(test_array, ",", "")
test_array

array(['1223', '111111'], dtype='<U6')

Indexing, working with 2D arrays

In [ ]:
sample_votes = np.array([775, 787, 918, 88, 166, 286, 2556, 324, 504, 402, 150, 164, 424, 918, 90, 133, 144, 93, 62, 180, 62, 148, 219, 506, 172, 415, 230, 1647, 4884, 133, 286, 540, 2556, 36, 244, 804, 679, 245, 345, 618, 1047, 627, 354, 244, 163, 808, 1720, 868, 520, 299])
sample_costs = np.array([800.0, 800.0, 800.0, 300.0, 600.0, 600.0, 600.0, 700.0, 550.0, 500.0, 600.0, 500.0, 450.0, 800.0, 650.0, 800.0, 700.0, 300.0, 400.0, 500.0, 600.0, 550.0, 600.0, 500.0, 750.0, 500.0, 650.0, 600.0, 750.0, 200.0, 500.0, 800.0, 600.0, 400.0, 300.0, 450.0, 850.0, 300.0, 400.0, 750.0, 450.0, 450.0, 800.0, 800.0, 800.0, 850.0, 400.0, 1200.0, 300.0, 300.0])

restaurants_data = np.array([sample_votes,sample_costs]).T

print("2D Array (votes,costs):\n",restaurants_data)
print("Shape:", restaurants_data.shape)
print("Dimensions:", restaurants_data.ndim)
print("Size:", restaurants_data.size)

2D Array (votes,costs):
 [[ 775.  800.]
 [ 787.  800.]
 [ 918.  800.]
 [  88.  300.]
 [ 166.  600.]
 [ 286.  600.]
 [2556.  600.]
 [ 324.  700.]
 [ 504.  550.]
 [ 402.  500.]
 [ 150.  600.]
 [ 164.  500.]
 [ 424.  450.]
 [ 918.  800.]
 [  90.  650.]
 [ 133.  800.]
 [ 144.  700.]
 [  93.  300.]
 [  62.  400.]
 [ 180.  500.]
 [  62.  600.]
 [ 148.  550.]
 [ 219.  600.]
 [ 506.  500.]
 [ 172.  750.]
 [ 415.  500.]
 [ 230.  650.]
 [1647.  600.]
 [4884.  750.]
 [ 133.  200.]
 [ 286.  500.]
 [ 540.  800.]
 [2556.  600.]
 [  36.  400.]
 [ 244.  300.]
 [ 804.  450.]
 [ 679.  850.]
 [ 245.  300.]
 [ 345.  400.]
 [ 618.  750.]
 [1047.  450.]
 [ 627.  450.]
 [ 354.  800.]
 [ 244.  800.]
 [ 163.  800.]
 [ 808.  850.]
 [1720.  400.]
 [ 868. 1200.]
 [ 520.  300.]
 [ 299.  300.]]
Shape: (50, 2)
Dimensions: 2
Size: 100


In [ ]:
restaurants_data.reshape(25,4)


array([[ 775.,  800.,  787.,  800.],
       [ 918.,  800.,   88.,  300.],
       [ 166.,  600.,  286.,  600.],
       [2556.,  600.,  324.,  700.],
       [ 504.,  550.,  402.,  500.],
       [ 150.,  600.,  164.,  500.],
       [ 424.,  450.,  918.,  800.],
       [  90.,  650.,  133.,  800.],
       [ 144.,  700.,   93.,  300.],
       [  62.,  400.,  180.,  500.],
       [  62.,  600.,  148.,  550.],
       [ 219.,  600.,  506.,  500.],
       [ 172.,  750.,  415.,  500.],
       [ 230.,  650., 1647.,  600.],
       [4884.,  750.,  133.,  200.],
       [ 286.,  500.,  540.,  800.],
       [2556.,  600.,   36.,  400.],
       [ 244.,  300.,  804.,  450.],
       [ 679.,  850.,  245.,  300.],
       [ 345.,  400.,  618.,  750.],
       [1047.,  450.,  627.,  450.],
       [ 354.,  800.,  244.,  800.],
       [ 163.,  800.,  808.,  850.],
       [1720.,  400.,  868., 1200.],
       [ 520.,  300.,  299.,  300.]])

In [ ]:
restaurants_data.reshape(10,10)


array([[ 775.,  800.,  787.,  800.,  918.,  800.,   88.,  300.,  166.,
         600.],
       [ 286.,  600., 2556.,  600.,  324.,  700.,  504.,  550.,  402.,
         500.],
       [ 150.,  600.,  164.,  500.,  424.,  450.,  918.,  800.,   90.,
         650.],
       [ 133.,  800.,  144.,  700.,   93.,  300.,   62.,  400.,  180.,
         500.],
       [  62.,  600.,  148.,  550.,  219.,  600.,  506.,  500.,  172.,
         750.],
       [ 415.,  500.,  230.,  650., 1647.,  600., 4884.,  750.,  133.,
         200.],
       [ 286.,  500.,  540.,  800., 2556.,  600.,   36.,  400.,  244.,
         300.],
       [ 804.,  450.,  679.,  850.,  245.,  300.,  345.,  400.,  618.,
         750.],
       [1047.,  450.,  627.,  450.,  354.,  800.,  244.,  800.,  163.,
         800.],
       [ 808.,  850., 1720.,  400.,  868., 1200.,  520.,  300.,  299.,
         300.]])

In [ ]:
restaurants_data.reshape(50,4)


ValueError: cannot reshape array of size 100 into shape (50,4)

In [ ]:
restaurants_data.reshape(25,2,2)



array([[[ 775.,  800.],
        [ 787.,  800.]],

       [[ 918.,  800.],
        [  88.,  300.]],

       [[ 166.,  600.],
        [ 286.,  600.]],

       [[2556.,  600.],
        [ 324.,  700.]],

       [[ 504.,  550.],
        [ 402.,  500.]],

       [[ 150.,  600.],
        [ 164.,  500.]],

       [[ 424.,  450.],
        [ 918.,  800.]],

       [[  90.,  650.],
        [ 133.,  800.]],

       [[ 144.,  700.],
        [  93.,  300.]],

       [[  62.,  400.],
        [ 180.,  500.]],

       [[  62.,  600.],
        [ 148.,  550.]],

       [[ 219.,  600.],
        [ 506.,  500.]],

       [[ 172.,  750.],
        [ 415.,  500.]],

       [[ 230.,  650.],
        [1647.,  600.]],

       [[4884.,  750.],
        [ 133.,  200.]],

       [[ 286.,  500.],
        [ 540.,  800.]],

       [[2556.,  600.],
        [  36.,  400.]],

       [[ 244.,  300.],
        [ 804.,  450.]],

       [[ 679.,  850.],
        [ 245.,  300.]],

       [[ 345.,  400.],
        [ 618.,  750.]],



In [ ]:
restaurants_data.shape

(50, 2)

In [ ]:
restaurants_data.reshape(5,-1).shape #This will find out the value of second dimension or second value. -1 is called empty placeholder

(5, 20)

In [ ]:
restaurants_data.reshape(6,-1).shape

ValueError: cannot reshape array of size 100 into shape (6,newaxis)

Indexing & Slicing

In [ ]:
print("Transpose of the 2D array:\n", restaurants_data.T)

Transpose of the 2D array:
 [[ 775.  787.  918.   88.  166.  286. 2556.  324.  504.  402.  150.  164.
   424.  918.   90.  133.  144.   93.   62.  180.   62.  148.  219.  506.
   172.  415.  230. 1647. 4884.  133.  286.  540. 2556.   36.  244.  804.
   679.  245.  345.  618. 1047.  627.  354.  244.  163.  808. 1720.  868.
   520.  299.]
 [ 800.  800.  800.  300.  600.  600.  600.  700.  550.  500.  600.  500.
   450.  800.  650.  800.  700.  300.  400.  500.  600.  550.  600.  500.
   750.  500.  650.  600.  750.  200.  500.  800.  600.  400.  300.  450.
   850.  300.  400.  750.  450.  450.  800.  800.  800.  850.  400. 1200.
   300.  300.]]


In [ ]:
restaurants_data[0]


array([775., 800.])

In [ ]:
restaurants_data[0,1]


np.float64(800.0)

In [ ]:
restaurants_data[0,:]


array([775., 800.])

In [ ]:
restaurants_data[:,1] #I want to select all the rows of first column


array([ 800.,  800.,  800.,  300.,  600.,  600.,  600.,  700.,  550.,
        500.,  600.,  500.,  450.,  800.,  650.,  800.,  700.,  300.,
        400.,  500.,  600.,  550.,  600.,  500.,  750.,  500.,  650.,
        600.,  750.,  200.,  500.,  800.,  600.,  400.,  300.,  450.,
        850.,  300.,  400.,  750.,  450.,  450.,  800.,  800.,  800.,
        850.,  400., 1200.,  300.,  300.])

In [ ]:
restaurants_data[:,:]


array([[ 775.,  800.],
       [ 787.,  800.],
       [ 918.,  800.],
       [  88.,  300.],
       [ 166.,  600.],
       [ 286.,  600.],
       [2556.,  600.],
       [ 324.,  700.],
       [ 504.,  550.],
       [ 402.,  500.],
       [ 150.,  600.],
       [ 164.,  500.],
       [ 424.,  450.],
       [ 918.,  800.],
       [  90.,  650.],
       [ 133.,  800.],
       [ 144.,  700.],
       [  93.,  300.],
       [  62.,  400.],
       [ 180.,  500.],
       [  62.,  600.],
       [ 148.,  550.],
       [ 219.,  600.],
       [ 506.,  500.],
       [ 172.,  750.],
       [ 415.,  500.],
       [ 230.,  650.],
       [1647.,  600.],
       [4884.,  750.],
       [ 133.,  200.],
       [ 286.,  500.],
       [ 540.,  800.],
       [2556.,  600.],
       [  36.,  400.],
       [ 244.,  300.],
       [ 804.,  450.],
       [ 679.,  850.],
       [ 245.,  300.],
       [ 345.,  400.],
       [ 618.,  750.],
       [1047.,  450.],
       [ 627.,  450.],
       [ 354.,  800.],
       [ 24

In [ ]:
#Rows 2 to rows 4, 2 & 4 both inclusive, all columns
restaurants_data[2:5,:]
#2:5 - 2 is included and but not the 5 when you define ranges in the python

array([[918., 800.],
       [ 88., 300.],
       [166., 600.]])

Fancy Indexing

In [ ]:
restaurants_data[:,1]


array([ 800.,  800.,  800.,  300.,  600.,  600.,  600.,  700.,  550.,
        500.,  600.,  500.,  450.,  800.,  650.,  800.,  700.,  300.,
        400.,  500.,  600.,  550.,  600.,  500.,  750.,  500.,  650.,
        600.,  750.,  200.,  500.,  800.,  600.,  400.,  300.,  450.,
        850.,  300.,  400.,  750.,  450.,  450.,  800.,  800.,  800.,
        850.,  400., 1200.,  300.,  300.])

In [ ]:
restaurants_data[:,1] > 500


array([ True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False, False,  True,  True,  True,  True, False,
       False, False,  True,  True,  True, False,  True, False,  True,
        True,  True, False, False,  True,  True, False, False, False,
        True, False, False,  True, False, False,  True,  True,  True,
        True, False,  True, False, False])

In [ ]:
#select first row, fifth row and seventh row
restaurants_data[[1,5,7],:]

array([[787., 800.],
       [286., 600.],
       [324., 700.]])

In [ ]:
#select first row, fifth row and seventh row
restaurants_data[[1,5,7]]

array([[787., 800.],
       [286., 600.],
       [324., 700.]])

In [ ]:
#Print all the value of array if the value > 500
restaurants_data[[ True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False, False,  True,  True,  True,  True, False,
       False, False,  True,  True,  True, False,  True, False,  True,
        True,  True, False, False,  True,  True, False, False, False,
        True, False, False,  True, False, False,  True,  True,  True,
        True, False,  True, False, False]]

array([[ 775.,  800.],
       [ 787.,  800.],
       [ 918.,  800.],
       [ 166.,  600.],
       [ 286.,  600.],
       [2556.,  600.],
       [ 324.,  700.],
       [ 504.,  550.],
       [ 150.,  600.],
       [ 918.,  800.],
       [  90.,  650.],
       [ 133.,  800.],
       [ 144.,  700.],
       [  62.,  600.],
       [ 148.,  550.],
       [ 219.,  600.],
       [ 172.,  750.],
       [ 230.,  650.],
       [1647.,  600.],
       [4884.,  750.],
       [ 540.,  800.],
       [2556.,  600.],
       [ 679.,  850.],
       [ 618.,  750.],
       [ 354.,  800.],
       [ 244.,  800.],
       [ 163.,  800.],
       [ 808.,  850.],
       [ 868., 1200.]])

In [ ]:
restaurants_data[restaurants_data[:,1] > 500]

array([[ 775.,  800.],
       [ 787.,  800.],
       [ 918.,  800.],
       [ 166.,  600.],
       [ 286.,  600.],
       [2556.,  600.],
       [ 324.,  700.],
       [ 504.,  550.],
       [ 150.,  600.],
       [ 918.,  800.],
       [  90.,  650.],
       [ 133.,  800.],
       [ 144.,  700.],
       [  62.,  600.],
       [ 148.,  550.],
       [ 219.,  600.],
       [ 172.,  750.],
       [ 230.,  650.],
       [1647.,  600.],
       [4884.,  750.],
       [ 540.,  800.],
       [2556.,  600.],
       [ 679.,  850.],
       [ 618.,  750.],
       [ 354.,  800.],
       [ 244.,  800.],
       [ 163.,  800.],
       [ 808.,  850.],
       [ 868., 1200.]])

In [ ]:
restaurants_data[restaurants_data[:,0] < 400]

array([[ 88., 300.],
       [166., 600.],
       [286., 600.],
       [324., 700.],
       [150., 600.],
       [164., 500.],
       [ 90., 650.],
       [133., 800.],
       [144., 700.],
       [ 93., 300.],
       [ 62., 400.],
       [180., 500.],
       [ 62., 600.],
       [148., 550.],
       [219., 600.],
       [172., 750.],
       [230., 650.],
       [133., 200.],
       [286., 500.],
       [ 36., 400.],
       [244., 300.],
       [245., 300.],
       [345., 400.],
       [354., 800.],
       [244., 800.],
       [163., 800.],
       [299., 300.]])

# **Very simple numpy operations**
sum
mean
min
max
std

In [ ]:
restaurants_data

array([[ 775.,  800.],
       [ 787.,  800.],
       [ 918.,  800.],
       [  88.,  300.],
       [ 166.,  600.],
       [ 286.,  600.],
       [2556.,  600.],
       [ 324.,  700.],
       [ 504.,  550.],
       [ 402.,  500.],
       [ 150.,  600.],
       [ 164.,  500.],
       [ 424.,  450.],
       [ 918.,  800.],
       [  90.,  650.],
       [ 133.,  800.],
       [ 144.,  700.],
       [  93.,  300.],
       [  62.,  400.],
       [ 180.,  500.],
       [  62.,  600.],
       [ 148.,  550.],
       [ 219.,  600.],
       [ 506.,  500.],
       [ 172.,  750.],
       [ 415.,  500.],
       [ 230.,  650.],
       [1647.,  600.],
       [4884.,  750.],
       [ 133.,  200.],
       [ 286.,  500.],
       [ 540.,  800.],
       [2556.,  600.],
       [  36.,  400.],
       [ 244.,  300.],
       [ 804.,  450.],
       [ 679.,  850.],
       [ 245.,  300.],
       [ 345.,  400.],
       [ 618.,  750.],
       [1047.,  450.],
       [ 627.,  450.],
       [ 354.,  800.],
       [ 24

In [ ]:
restaurants_data.sum(axis=0) #columns addition - axis define the direction

array([30583., 29350.])

In [ ]:
restaurants_data.sum(axis=1) #rows addition - axis define the direction

array([1575., 1587., 1718.,  388.,  766.,  886., 3156., 1024., 1054.,
        902.,  750.,  664.,  874., 1718.,  740.,  933.,  844.,  393.,
        462.,  680.,  662.,  698.,  819., 1006.,  922.,  915.,  880.,
       2247., 5634.,  333.,  786., 1340., 3156.,  436.,  544., 1254.,
       1529.,  545.,  745., 1368., 1497., 1077., 1154., 1044.,  963.,
       1658., 2120., 2068.,  820.,  599.])

In [ ]:
restaurants_data.mean(axis=0)

array([611.66, 587.  ])

In [ ]:
restaurants_data.mean(axis=1)

array([ 787.5,  793.5,  859. ,  194. ,  383. ,  443. , 1578. ,  512. ,
        527. ,  451. ,  375. ,  332. ,  437. ,  859. ,  370. ,  466.5,
        422. ,  196.5,  231. ,  340. ,  331. ,  349. ,  409.5,  503. ,
        461. ,  457.5,  440. , 1123.5, 2817. ,  166.5,  393. ,  670. ,
       1578. ,  218. ,  272. ,  627. ,  764.5,  272.5,  372.5,  684. ,
        748.5,  538.5,  577. ,  522. ,  481.5,  829. , 1060. , 1034. ,
        410. ,  299.5])

In [ ]:
cost

array(['800.0', '800.0', '800.0', '300.0', '600.0', '600.0', '600.0',
       '700.0', '550.0', '500.0'], dtype='<U5')

In [ ]:
np.where(cost > 500)

UFuncTypeError: ufunc 'greater' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes._PyLongDType'>) -> None

In [ ]:
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12])
print((p + q)[0][0])

10


In [ ]:
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])[1][1])

1.0
